### ISSUE TITLE
not depend on HOMER

### ISSUE THREAD

**Issue by mbstadler** [fmicompbio/monaLisa#28]
- re-implement sequence-composition-corrected motif counting, as in `findMotifsGenome.pl` from HOMER
This would make `monaLisa` independent of Homer, avoid the re-scanning of sequences for each bin, make it easier to install/use the package and submit to bioc

**Comment by machlabd** [comment]
Shall we close this issue?

**Comment by mbstadler** [comment]
Yes, either now with a reference to the branch, or later when we merge this branch into master.

**Comment by machlabd** [comment]
Ok, let's do it when we merge into master then.

**Comment by mbstadler** [comment]
with the merge of #37 (https://github.com/fmicompbio/monaLisa/commit/6687d57a436d9a5c7575d45e0f09afdb4b138263) this has been done
