### ISSUE TITLE
Add options for binned motif enrichment

### ISSUE THREAD

**Issue by machlabd** [fmicompbio/monaLisa#35]
Would be useful to have the option to do the binned approach in these 3 ways:
1) enrichment in bin (fg) vs all other remaining bins (bg) (default)
2) enrichment in bin vs all bins
3) enrichment in bin vs the central bin
4) enrichment in bin vs genome (sampling regions from genome as HOMER: item 5. on http://homer.ucsd.edu/homer/ngs/peakMotifs.html, section "How findMotifsGenome.pl works")

**Comment by mbstadler** [comment]
Implemented in https://github.com/fmicompbio/monaLisa/commit/0b1a6604a034fefa23439742db9c0e071a1cba8d
