### ISSUE TITLE
Add legend with bin labels to heatmap

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/monaLisa#62]
Add a legend (maybe optionally) with the bin labels to the heatmaps.

**Comment by danymukesha** [comment]
@csoneson, @mbstadler 
The heatmaps already seem to have the legend for bin labels (it is just currently set to `show_legend = FALSE`). I think the only thing left to do is to add an optional parameter to the function that generate the heatmaps.

For example, in the case of the [plotMotifHeatmaps](https://fmicompbio.github.io/monaLisa/reference/plotMotifHeatmaps.html) function, we could add the `show_bin_legend = FALSE` parameter like this: `plotMotifHeatmaps <- function(..., show_bin_legend = FALSE, ...)`, keeping it optional by default."

It would look something like this. If `TRUE`, it would show a legend for the bin labels:
![image](https://github.com/user-attachments/assets/bd879f75-a56b-4a2e-9088-40c9537cfefd)

Did I get it right?

Perhaps the position of the legends for bin labels should be adjusted as well, maybe placing them in a single column with other legends!

**Comment by mbstadler** [comment]
Yes, we agree with you, exposing that additional parameter seems all that would be needed. You are also right that it would be nice if the legend could be placed above additional existing legends.

**Comment by csoneson** [comment]
Addressed in #79
