### ISSUE TITLE
how to set the text size of the motif names in plotMotifHeatmaps function?

### ISSUE THREAD

**Issue by xflicsu** [fmicompbio/monaLisa#63]

**Comment by mbstadler** [comment]
I have added a modification (see #64) to `monaLisa` version 1.7.1 (current `devel` branch of Bioconductor) that allows you to modify the motif name text size using:
```
plotMotifHeatmaps(..., row_names_gp = gpar(fontsize = 12))
```

The `...` argument has been existing for `plotMotifHeatmaps` to forward additional parameters to `ComplexHeatmap::Heatmap` for the main heatmap, but modifying motif names did not work in versions 1.7.0 and before as the motif names are provided by a separate heatmap (one that is used to optionally highlight some of the motifs).

In version 1.7.1, the additional arguments are now forwarded to all `ComplexHeatmap::Heatmap` calls, and thus changing motif name size is now working as expected.

This feature will become available with `monalLisa` version 1.8.0 upon release of Bioconductor 3.18 around mid-October 2023. If you want to already use it now, you can use Bioconductor 3.18 (devel) branch as described here: https://contributions.bioconductor.org/use-devel.html (preferred) or install `monaLisa` directly from GitHub using `remotes::install_github('fmicompbio/monaLisa')` (easier now, but not recommended as it will leave you with a mixture of release and devel packages in your library). 

Please let me know if that resolves your issue.

**Comment by mbstadler** [comment]
I will close the issue for the moment. Please feel free to re-open it if needed.
