### ISSUE TITLE
dumpJaspar function

### ISSUE THREAD

**Issue by Smartmandm** [fmicompbio/monaLisa#65]
Hello,

I have used the dumpJaspar function successfully to obtain a HOMER-compatible motif file prob. matrix, starting from a Jaspar frequency matrix : 

new_motif <- dumpJaspar(filename = "MA0138_2_RE1.motif", pkg = "JASPAR2022", opts = list(ID = c("MA0138.2")))

Now if I have a "custom" frequency matrix in the same format as the jaspar matrix , **but that is not present in the jaspar database** :

>Half_RE1
A  [   211     58     76   1452     34    122   1575      3     35 ]
C  [   174    269   1366     30     44    978      7   1586   1481 ]
G  [   366    146     50     94   1516    323     12     12     20 ]
T  [   840   1124    105     26     10    182     12      5     70 ]

Is there a way to use the function dumpJaspar in order to convert it to Homer-compatible motif file? 

I have read the documentation in the Homer page about making custom motif file, but it is not 100% clear to me as how to proceed.

Thank you,

Marie

**Comment by machlabd** [comment]
Hi Marie,

The `dumpJaspar` function in its current implementation can only take in a known database of motifs like `Jaspar` to create the needed `Homer` format of the motifs. Below are some suggestions depending on if you are using `monaLisa` or `Homer` to do your motif analysis:

1) using `monaLisa`: If you have a new motif of your own and would like to add that into your analysis in `monalisa`, you can simply convert it to a `PFMatrix` object. Below is an example of how you would do that.

```
library(TFBSTools)
# construct PFMatrix; See TFBSTools::PFMatrix for more details
# ... if you plan on using this motif with other ones, be sure to have the same
# ... background, which is uniform by default (0.25 for ACGT).
pfmNew <- PFMatrix(ID="yourID", name="Half_RE1", 
        bg=c(A=0.25, C=0.25, G=0.25, T=0.25),
        profileMatrix=matrix(c(211L, 58L,  76L,  1452L, 34L,  122L, 1575L, 3L,  35L,
                    174L, 269L, 1366L, 30L,  44L,  978L, 7L,  1586L, 1481L,
                    366L, 146L, 50L,  94L,  1516L, 323L, 12L,  12L,  20L,
                    840L, 1124L, 105L, 26L,  10L,  182L, 12L,  5L,  70L),
                   byrow=TRUE, nrow=4,
                   dimnames=list(c("A", "C", "G", "T"))
        )
)

pfmNew
# An object of class PFMatrix
# ID: yourID
# Name: Half_RE1
# Matrix Class: Unknown
# strand: +
#  Tags: 
#  list()
# Background: 
#  A  C  G  T 
# 0.25 0.25 0.25 0.25 
# Matrix: 
#  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
# A 211  58  76 1452  34 122 1575  3  35
# C 174 269 1366  30  44 978  7 1586 1481
# G 366 146  50  94 1516 323  12  12  20
# T 840 1124 105  26  10 182  12  5  70

# add to your list of PFMs if they exist
# ... get PFMs from JASPAR2020 package (vertebrate subset)
library(JASPAR2020)
pfms <- getMatrixSet(JASPAR2020,
           opts = list(matrixtype = "PFM",
                 tax_group = "vertebrates"))
# ... add pfmNew to the list 
# ... ... we first convert pfmNew to a PFMatrixList object
pfmNew <- PFMatrixList(yourID = pfmNew)
pfms <- c(pfms, pfmNew)
pfms
# PFMatrixList of length 747
# names(747): MA0004.1 MA0006.1 MA0019.1 MA0029.1 MA0030.1 ... MA0748.2 MA0528.2 MA0609.2 yourID

# convert PFMs to PWMs
pwms <- toPWM(pfms)

# continue analysis with monaLisa as in https://fmicompbio.github.io/monaLisa/articles/monaLisa.html#prepare-motif-enrichment-analysis
```


2) using `Homer`: you can make use of this undocumented internal function `monaLisa:::.dumpPWMsToHomer2File`, which accepts a `PWMatrixList`, (see https://github.com/fmicompbio/monaLisa/blob/3985e84e7cce85e5eeb6308d6688b393e55e75f6/R/motif_finding.R#L13-L51) or you can look at the source code of `dumpJaspar()` (specifically https://github.com/fmicompbio/monaLisa/blob/3985e84e7cce85e5eeb6308d6688b393e55e75f6/R/motif_enrichment_HOMER.R#L110-L135, in which `siteList` is a `PFMatrixList`; see the previous example above on how to construct this object). I am also linking to what I found on the `Homer` webpage regarding their file formats http://homer.ucsd.edu/homer/motif/creatingCustomMotifs.html, but if this doesn’t help maybe you can contact the authors of `Homer` directly.


Best,
Dania

**Comment by machlabd** [comment]
Hi Marie,

I am closing this issue for now. If you have further questions feel free to re-open it.

Best,
Dania

**Comment by Smartmandm** [comment]
Thanks a lot for your answer, it was very helpful!
