### ISSUE TITLE
Issue with JASPAR2024

### ISSUE THREAD

**Issue by nsoriano2** [fmicompbio/monaLisa#68]
Hello,
It seems to me that monaLisa is not working with JASPAR2024.

````
library(monaLisa)
dumpJaspar(filename = "MA0886.2.txt", pkg = "JASPAR2024",
opts = list(ID = c("MA0886.2")));

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getMatrixSet’ for signature ‘"function"’
````

**Comment by machlabd** [comment]
Hi @nsoriano2 , 

Thank you for bringing this issue to our attention! It seems the way one interacts with `JASPAR2024` has changed and is causing `dumpJAspar()` to fail when extracting the `PFMatrixList` (previous `JASPAR`packages should still work). We are currently looking into how to best fix this, and will update you as soon as we have implemented a fix. 

Best,
Dania

**Comment by machlabd** [comment]
Hi @nsoriano2,

A fix to this issue has been implemented in `monaLisa` and pushed to BioC 3.18 (current bioconductor, and `monaLisa 1.8.1`) as well as to the devel branch (Bioc 3.19 and `monaLisa 1.9.1`). You can now download either binaries directly from Bioconductor.
 
Thanks again for making us aware of this problem!

Best,
Dania

**Comment by nsoriano2** [comment]
Many thanks for this quick fix !

**Comment by machlabd** [comment]
Great, I'll close this issue now, but if you run into more problems feel free to come back here or open a new issue.

Best,
Dania
