### ISSUE TITLE
Heatmap logo annotation broken using grid.grabExpr()

### ISSUE THREAD

**Issue by IStevant** [fmicompbio/monaLisa#75]
Hey,

I would like to build a figure with multiple monaLisa heatmaps side by side so I use `grid.grabExpr()` to store the complexeHeatmap objects generated with `plotMotifHeatmaps()` and generate the figure with cowplot.

It works perfectly if I don't plot the logos, but if I set `show_seqlogo = TRUE`, several logos are missing:
![shot-2024-04-24_17-19-09](https://github.com/fmicompbio/monaLisa/assets/25080573/f0f80b17-7abe-4807-9501-07af6d78d902)

When I open the pdf in Inkscape, I can see that they are present but stacked on top of each other.

Example of code with `seSel` being the result of `calcBinnedMotifEnrR()`
```
heatmap <- grid.grabExpr(plotMotifHeatmaps(
	x = seSel,
	which.plots = c("log2enr", "negLog10Padj"), 
	show_seqlogo = TRUE,
	width = 1.3, 
	maxEnr = 1.5, 
	maxSig = 100,
	width.seqlogo = 1.8
))

cowplot::save_plot(
	"test.pdf",
	heatmap,
	base_width=25,
	base_height=20,
	units = c("cm")
)
```
It works fine with a regular pdf export using `pdf()`.

**Comment by csoneson** [comment]
Hi @IStevant - I can reproduce the issue running your code above. However, `grid.grabExpr` gives me a warning message that says 

```
Warning message:
In grabDL(warn, wrap, wrap.grobs, ...) :
  one or more grobs overwritten (grab WILL not be faithful; try 'wrap.grobs = TRUE')
```

And indeed setting `wrap.grobs = TRUE` in the call to `grid.grabExpr()` solves the issue for me (there are no more overlapping seqlogos).

**Comment by IStevant** [comment]
Hi @csoneson,

I missed this warning message, it works perfectly, thank you very much !

Best,

Isabelle
