### ISSUE TITLE
option to plot enrichment heat map without motifs enriched in central bin

### ISSUE THREAD

**Issue by LukasBurger** [fmicompbio/monaLisa#9]
Also a reminder of our brief conversation in the canteen, it would be
nice to have an option when plotting the heat map to not plot the values
 for the motifs enriched [only] in the central bin.

**Comment by mbstadler** [comment]
This is related to #35 and should probably be addressed together

**Comment by mbstadler** [comment]
#35 is now done (see https://github.com/fmicompbio/monaLisa/commit/0b1a6604a034fefa23439742db9c0e071a1cba8d), and we have a todo item in #36 to illustrate in the vignette how subsetting the `SummarizedExperiment` can achieve that, without adding additional parameters to `plotMotifHeatmaps`, so I'll close it for now (it can be reopenend if necessary).
